---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  install: {}
  interval: 30s
  targetNamespace: production
  values:
    image:
      tag: 2.9.17
    ingress:
      host: production.devops-toolkit.172.20.85.210.xip.io
